<?php

declare(strict_types=1);

namespace App\Observers;

use App\Models\ShoppingList;
use Illuminate\Support\Str;

/**
 * Class ShoppingListObserver
 *
 * @package App\Observers
 */
class ShoppingListObserver
{
    /**
     * Handle the ShoppingList "creating" event.
     *
     * @param  \App\Models\ShoppingList  $shoppingList
     *
     * @return void
     */
    public function creating(ShoppingList $shoppingList)
    {
        // We do not expect a UUID too exist on creating (as this should be autogenerated)
        $shoppingList->uuid = Str::uuid()->toString();
    }
}
