<?php

declare(strict_types=1);

namespace App\Observers;

use App\Models\ShoppingItem;
use Illuminate\Support\Str;

/**
 * Class ShoppingItemObserver
 *
 * @package App\Observers
 */
class ShoppingItemObserver
{
    /**
     * Handle the ShoppingList "creating" event.
     *
     * @param  \App\Models\ShoppingItem  $shoppingItem
     *
     * @return void
     */
    public function creating(ShoppingItem $shoppingItem): void
    {
        // We do not expect a UUID too exist on creating (as this should be autogenerated)
        $shoppingItem->uuid = Str::uuid()->toString();
    }
}
