<?php

declare(strict_types=1);

namespace App\Observers;

use App\Models\User;
use Illuminate\Support\Str;

/**
 * Class UserObserver
 *
 * @package App\Observers
 */
class UserObserver
{
    /**
     * Handle the User "creating" event.
     *
     * @param  \App\Models\User  $user
     *
     * @return void
     */
    public function creating(User $user)
    {
        // We do not expect a UUID too exist on creating (as this should be autogenerated)
        $user->uuid = Str::uuid();
    }
}
